# Secret template for API Gateway
# Create this file: k8s/api-gateway/templates/secrets.yaml

{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secrets
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
{{- end }}
